format = '$all'
right_format = '$username$hostname'


[aws]
symbol = "  "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red) '

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)@'
disabled = false
show_always = true

[character] # The name of the modu
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold bright-black"

[os.symbols]
Arch = "󰚌 "

[package]
symbol = "󰏗 "
disabled = true

[python]
symbol = "󰌠 "

[rust]
symbol = " "

[shell]
disabled = true
